name: Copy getData file to Another Repo

on:
  push:
    branches: [Jayant-Chaurasiya-ver-1]    

jobs:
  copy-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3

    - name: Checkout target repository
      uses: actions/checkout@v3
      with:
        repository: Jayant-Chaurasiya/DEMO_ZIP_TOOL
        token: ${{ secrets.TARGET_REPO_TOKEN }}
        path: DEMO_ZIP_TOOL

    - name: Copy getData file to target repository demo folder
      run: |
        mkdir -p DEMO_ZIP_TOOL/Demo2
        cp  Demo/GetData.txt DEMO_ZIP_TOOL/Demo2

    - name: Commit and push if there are changes
      run: |
        cd DEMO_ZIP_TOOL
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        if git diff --quiet; then
          echo "No changes detected"
          exit 0
        fi

        git add demo2/getData
        git commit -m "Update getData file from source repository"
        git push origin main
